name: senhor_bolo
description: O terror da Sodiê Doces

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  font_awesome_flutter: ^9.2.0
  badges: ^2.0.1
  animations: ^2.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  shimmer_animation: ^2.1.0

  # Localização do usuário
  geocoding: ^2.0.1
  google_maps_flutter: ^2.0.11

  # API
  http: ^0.13.3
  connectivity: ^3.0.6

  #Armazenamento
  flutter_secure_storage: ^4.2.1
  sqflite_sqlcipher: ^2.1.0

  #Interface
  cool_alert: ^1.1.0

  #email
  url_launcher: ^6.0.12

  #Gerencia de estado
  provider: ^6.0.1

  # Outros
  mask_text_input_formatter: ^2.0.0
  password_strength: ^0.2.0
  credit_card_validator: ^2.0.0
  cached_network_image: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  #Imagens
  assets:
    - images/logo_login.png
    - images/bolo_login.png
    - images/mastercard.png
    - images/visa.png
    - images/card.png
    - images/banner_teste.png
    - images/logoMarrom.png
    - images/boloBoasVindas.png
    - images/splash_image.png
    - images/erroConexao.png
    - images/pedido_entrega.png
    - images/pedido_entregue.png
    - images/pedido_preparacao.png
    - images/pedido_recebido.png

  #Fontes
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 500
        - asset: fonts/Raleway-ExtraBold.ttf
          weight: 900 
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf